
import { jsPDF } from "jspdf";

export default function generatePdf({
  student,
  benefit,
  benefitCode,
}) {
  const pdf = new jsPDF();

  // Header
  pdf.setFont("helvetica", "bold");
  pdf.setFontSize(20);
  pdf.text("HAPROVEN", 20, 20);

  pdf.setFontSize(14);
  pdf.text("Student Benefit Pass", 20, 30);

  // Line
  pdf.line(20, 35, 190, 35);

  // Student Information
  pdf.setFontSize(12);

  pdf.text(`Student Name : ${student.fullName}`, 20, 50);
  pdf.text(`Haproven ID : ${student.haprovenId}`, 20, 60);
  pdf.text(`Email : ${student.email}`, 20, 70);
  pdf.text(`Institute : ${student.institute.name}`, 20, 80);

  // Benefit Information
  pdf.text(`Benefit Code : ${benefitCode}`, 20, 100);
  pdf.text(`Benefit : ${benefit.title}`, 20, 110);
  pdf.text(`Certificate : ${benefit.certificate}`, 20, 120);

  pdf.text(
    `Discount : ${
      benefit.discount.type === "Percentage"
        ? benefit.discount.value + "%"
        : "Free"
    }`,
    20,
    130
  );

  pdf.text(
    `Valid Till : ${benefit.validity.endDate}`,
    20,
    140
  );

  // Terms
  pdf.setFont("helvetica", "bold");
  pdf.text("Terms & Conditions", 20, 160);

  pdf.setFont("helvetica", "normal");

  pdf.text(
    "- Benefit is valid only for the registered student.",
    20,
    170
  );

  pdf.text(
    "- Institute may verify this benefit before approval.",
    20,
    180
  );

  pdf.text(
    "- This document is issued by Haproven.",
    20,
    190
  );

  // Footer
  pdf.setFontSize(10);

  pdf.text(
    "Generated by Haproven Student Benefits System",
    20,
    280
  );

  // Download
  pdf.save(`${benefitCode}.pdf`);
}
